package com.softicar.platform.core.module;

import com.softicar.platform.common.core.interfaces.ITestMarker;

public enum CoreTestMarker implements ITestMarker {

	PAGE_HEADER_USER_POPOVER,
	PAGE_HEADER_USER_POPOVER_BUTTON,
	PAGE_HEADER_USER_POPOVER_LOGOUT_BUTTON,
	PAGE_HEADER_USER_POPOVER_PROFILE_PAGE_BUTTON,
	PAGE_HEADER_USER_POPOVER_SESSION_PAGE_BUTTON,

	PAGE_NAVIGATION_FOLDER_TITLE_DIV,
	PAGE_NAVIGATION_LINK_DIV,
	PAGE_NAVIGATION_PAGE_CONTENT_DIV,

	PAGE_SERVICE_LOGIN_ERROR_MESSAGE_ELEMENT,
	PAGE_SERVICE_LOGIN_FORM,
	PAGE_SERVICE_LOGIN_LOGIN_BUTTON,
	PAGE_SERVICE_LOGIN_PASSWORD_INPUT,
	PAGE_SERVICE_LOGIN_USER_INPUT,

	START_PAGE_MAIN_ELEMENT,

	STORED_FILE_DOWNLOAD_FILE_BUTTON,
	STORED_FILE_REMOVE_FILE_BUTTON,

	USER_PREFERENCES_NAVIGATION_FOLDER_COLLAPSE_MODE,
	USER_PREFERENCES_PREFERRED_POPUP_PLACEMENT,
	USER_PREFERENCES_SAVE_BUTTON,
}
