package com.softicar.platform.core.module;

import com.softicar.platform.common.core.interfaces.ITestMarker;

public enum CoreTestMarker implements ITestMarker {

	PAGE_NAVIGATION_FOLDER_TITLE_DIV,
	PAGE_NAVIGATION_PAGE_CONTENT_DIV,
	PAGE_NAVIGATION_PAGE_LINK_DIV,

	PAGE_SERVICE_LOGIN_ERROR_MESSAGE_ELEMENT,
	PAGE_SERVICE_LOGIN_LOGIN_BUTTON,
	PAGE_SERVICE_LOGIN_PASSWORD_INPUT,
	PAGE_SERVICE_LOGIN_USER_INPUT,

	START_PAGE_MAIN_ELEMENT,

	STORED_FILE_ADD_FILE_ELEMENT,
	STORED_FILE_DOWNLOAD_FILE_BUTTON,
	STORED_FILE_REMOVE_FILE_BUTTON,
	STORED_FILE_UPLOAD_FORM,
}
