
const AJAX_CSS_PSEUDO_CLASS_HIDDEN = 'hidden';

const AJAX_REQUEST_LOGIN           = 0;
const AJAX_REQUEST_CREATE_DOCUMENT = 1;
const AJAX_REQUEST_KEEP_ALIVE      = 2;
const AJAX_REQUEST_TIMEOUT         = 5;
const AJAX_REQUEST_DOM_EVENT       = 6;
const AJAX_REQUEST_DRAG_AND_DROP   = 7;
const AJAX_REQUEST_UPLOAD          = 8;
const AJAX_REQUEST_RESOURCE        = 9;
const AJAX_REQUEST_AUTO_COMPLETE   = 10;

const DOM_VK_TAB    = 9;
const DOM_VK_ENTER  = 13;
const DOM_VK_ESCAPE = 27;
const DOM_VK_SPACE  = 32;
const DOM_VK_UP     = 38;
const DOM_VK_DOWN   = 40;

const KEEP_ALIVE_REQUEST_DELAY = 3*60*1000

const HTTP_REQUEST_STATE_UNSET            = 0; 
const HTTP_REQUEST_STATE_OPENED           = 1; 
const HTTP_REQUEST_STATE_HEADERS_RECEIVED = 2; 
const HTTP_REQUEST_STATE_LOADING          = 3; 
const HTTP_REQUEST_STATE_DONE             = 4; 

const HTTP_STATUS_SUCCESS = 200;
const HTTP_STATUS_GONE = 410;

const TIMEOUT_RETRY_DELAY = 500;
