
let AJAX_REQUEST_LOGIN           = 0;
let AJAX_REQUEST_CREATE_DOCUMENT = 1;
let AJAX_REQUEST_KEEP_ALIVE      = 2;
let AJAX_REQUEST_TIMEOUT         = 5;
let AJAX_REQUEST_DOM_EVENT       = 6;
let AJAX_REQUEST_DRAG_AND_DROP   = 7;
let AJAX_REQUEST_UPLOAD          = 8;
let AJAX_REQUEST_RESOURCE        = 9;
let AJAX_REQUEST_AUTO_COMPLETE   = 10;

let DOM_VK_TAB    = 9;
let DOM_VK_ENTER  = 13;
let DOM_VK_ESCAPE = 27;
let DOM_VK_SPACE  = 32;
let DOM_VK_UP     = 38;
let DOM_VK_DOWN   = 40;

let LOCK_REASON_DOM_EVENT     = 0;
let LOCK_REASON_TIMEOUT       = 1;
let LOCK_REASON_KEEP_ALIVE    = 2;
let LOCK_REASON_DRAG_AND_DROP = 3;
let LOCK_REASON_UPLOAD        = 4;

let KEEP_ALIVE_REQUEST_DELAY = 3*60*1000
