
const AJAX_CSS_PSEUDO_CLASS_HIDDEN = 'hidden';

const AJAX_REQUEST_KEEP_ALIVE      = 2;
const AJAX_REQUEST_TIMEOUT         = 5;
const AJAX_REQUEST_DOM_EVENT       = 6;
const AJAX_REQUEST_DRAG_AND_DROP   = 7;
const AJAX_REQUEST_UPLOAD          = 8;

const DOM_MODIFIER_ALT = 'Alt';
const DOM_MODIFIER_CONTROL = 'Control';
const DOM_MODIFIER_META = 'Meta';
const DOM_MODIFIER_SHIFT = 'Shift';

const KEEP_ALIVE_REQUEST_DELAY = 3*60*1000

const HTTP_REQUEST_STATE_UNSET            = 0; 
const HTTP_REQUEST_STATE_OPENED           = 1; 
const HTTP_REQUEST_STATE_HEADERS_RECEIVED = 2; 
const HTTP_REQUEST_STATE_LOADING          = 3; 
const HTTP_REQUEST_STATE_DONE             = 4; 

const HTTP_STATUS_SUCCESS = 200;
const HTTP_STATUS_GONE = 410;
