package com.softicar.platform.db.core.dbms.mysql;

public enum DbMysqlPrivilege {

	ALL("ALL"),
	ALTER("ALTER"),
	ALTER_ROUTINE("ALTER ROUTINE"),
	CREATE("CREATE"),
	CREATE_ROLE("CREATE ROLE"),
	CREATE_ROUTINE("CREATE ROUTINE"),
	CREATE_TABLESPACE("CREATE TABLESPACE"),
	CREATE_TEMPORARY_TABLES("CREATE TEMPORARY TABLES"),
	CREATE_USER("CREATE USER"),
	CREATE_VIEW("CREATE VIEW"),
	DELETE("DELETE"),
	DROP("DROP"),
	DROP_ROLE("DROP ROLE"),
	EVENT("EVENT"),
	EXECUTE("EXECUTE"),
	FILE("FILE"),
	GRANT_OPTION("GRANT OPTION"),
	INDEX("INDEX"),
	INSERT("INSERT"),
	LOCK_TABLES("LOCK TABLES"),
	PROCESS("PROCESS"),
	PROXY("PROXY"),
	REFERENCES("REFERENCES"),
	RELOAD("RELOAD"),
	REPLICATION_CLIENT("REPLICATION CLIENT"),
	REPLICATION_SLAVE("REPLICATION SLAVE"),
	SELECT("SELECT"),
	SHOW_DATABASES("SHOW DATABASES"),
	SHOW_VIEW("SHOW VIEW"),
	SHUTDOWN("SHUTDOWN"),
	SUPER("SUPER"),
	TRIGGER("TRIGGER"),
	UPDATE("UPDATE"),
	USAGE("USAGE"),
	//
	;

	private String identifier;

	private DbMysqlPrivilege(String identifier) {

		this.identifier = identifier;
	}

	public String getIdentifier() {

		return identifier;
	}

	@Override
	public String toString() {

		return identifier;
	}
}
