package com.softicar.platform.dom;

import com.softicar.platform.common.core.interfaces.ITestMarker;

public enum DomTestMarker implements ITestMarker {

	DAY_INPUT,

	DAY_TIME_INPUT,

	IMAGE_VIEWER_CANVAS,
	IMAGE_VIEWER_IMAGE,
	IMAGE_VIEWER_IMAGE_HOLDER,
	IMAGE_VIEWER_NEXT_PAGE_BUTTON,
	IMAGE_VIEWER_PAGE_INDICATOR,
	IMAGE_VIEWER_PREVIOUS_PAGE_BUTTON,
	IMAGE_VIEWER_ROTATE_LEFT_BUTTON,
	IMAGE_VIEWER_ROTATE_RIGHT_BUTTON,
	IMAGE_VIEWER_TAG,
	IMAGE_VIEWER_TAG_CAPTION,
	IMAGE_VIEWER_TAGS_TOGGLE_BUTTON,
	IMAGE_VIEWER_ZOOM_IN_BUTTON,
	IMAGE_VIEWER_ZOOM_OUT_BUTTON,

	MODAL_DIALOG_CONTENT,
	MODAL_DIALOG_FRAME,
	MODAL_DIALOG_POPUP,
	MODAL_ALERT_CLOSE_BUTTON,
	MODAL_CONFIRM_CANCEL_BUTTON,
	MODAL_CONFIRM_OKAY_BUTTON,
	MODAL_PROMPT_INPUT_ELEMENT,

	PAGEABLE_TABLE,
	PAGEABLE_TABLE_NAVIGATION,
	PAGEABLE_TABLE_NAVIGATION_EXPORT_BUTTON,
	PAGEABLE_TABLE_NAVIGATION_PAGE_NEXT_BUTTON,
	PAGEABLE_TABLE_NAVIGATION_PAGE_NUMBER_BUTTON,
	PAGEABLE_TABLE_NAVIGATION_PAGE_PREV_BUTTON,

	POPUP_BACKDROP,
	POPUP_FRAME,
	POPUP_FRAME_CLOSE_BUTTON,
	POPUP_FRAME_HEADER,
	POPUP_COMPOSITOR_DIALOG_BUTTON_CANCEL,
	POPUP_COMPOSITOR_DIALOG_BUTTON_CLOSE_ALL,
	POPUP_COMPOSITOR_DIALOG_BUTTON_CLOSE_PARENT_ONLY,

	SIMPLE_VALUE_SELECT,

	TIME_INPUT
}
